services:
  rippotai-backend:
    image: ghcr.io/rocklimedev/rippotai-backend:latest
    pull_policy: always
    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - .env

    volumes:
      - ./uploads:/usr/src/app/uploads

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000"]
      interval: 30s
      timeout: 5s
      retries: 3
