version: "3.9"

services:
  rippotai-backend:
    image: ghcr.io/rocklimedev/rippotai-backend:latest
    container_name: rippotai-backend
    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - .env

    volumes:
      - ./uploads:/app/uploads

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
