import type { Project } from "./types";

/**
 * Portfolio. Order = order on /projects; each entry gets its own page at /projects/[slug].
 * Slugs, copy, locations and scopes mirror rippotaiarchitecture.com (api-v2 /projects) so
 * existing URLs keep working. `shape` is the planned grid tile on /projects:
 * F = full-bleed, W = wide (65%), H = horizontal (half), V = vertical (35%).
 * `gallery` prefers the curated local WebP set in /public/images; `archive` holds the
 * original CDN photographs for those projects (unused by default, available to the admin).
 */
export const projects: Project[] = [
  {
    slug: "guptas-residence-ii",
    name: "Tropical Home",
    category: "residential",
    type: "Residential",
    location: "GK II, New Delhi",
    scope: "Interior Designing",
    status: "Completed",
    cover: "/images/p_tropical.webp",
    banner: "/images/hero3.webp",
    shape: "F",
    featured: true,
    summary:
      "The Tropical Home unfolds as a layered dining experience in Greater Kailash II, where nature, art, and everyday living come together with quiet confidence. Botanical motifs form the visual heart of the space, introducing softness and movement against a restrained backdrop of warm beige, textured surfaces, and natural wood.",
    details: [
      "Rust-toned seating adds depth, while glass pendants cast a gentle glow over the dining table, making the setting feel intimate and inviting. The composition is refined without feeling formal. Clean ceiling lines, filtered daylight, and carefully balanced materials allow the room to feel expressive, comfortable, and naturally connected to its tropical character.",
    ],
    gallery: [
      "/images/hero3.webp",
      "/images/L3.webp",
      "/images/d1.webp",
      "/images/L9.webp",
      "/images/s15.webp",
      "/images/d8.webp",
      "/images/s9.webp",
    ],
    archive: [
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence_two/1.jpg",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence_two/2.jpg",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence_two/3.jpg",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence_two/4.jpg",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence_two/5.jpg",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence_two/6.jpg",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence_two/7.jpg",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence_two/8.jpg",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence_two/9.jpg",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence_two/10.jpg",
    ],
  },
  {
    slug: "the-inner-house",
    name: "The Inner House",
    category: "residential",
    type: "Residential",
    location: "Sunder Vihar, Delhi",
    scope: "Interior",
    status: "Completed",
    cover: "/images/p_inner.webp",
    banner: "/images/hero4.webp",
    shape: "V",
    featured: true,
    summary:
      "For this home in Sunder Vihar, we focused on creating a warm, minimal environment shaped by comfort, clarity, and everyday functionality. A soft palette of warm whites, muted beiges, and natural wood tones forms the foundation of the home. Herringbone wooden flooring introduces subtle movement, while diffused lighting and sheer curtains soften the interiors.",
    details: [
      "Clean lines, gentle curves, and integrated furniture maintain visual continuity without making the spaces feel rigid or overly designed. The bedroom is conceived as a quiet retreat, with ambient cove lighting and a curved chaise adding softness and character. A minimal floating workspace extends naturally within the room, keeping the composition light and functional.",
    ],
    gallery: ["/images/hero4.webp", "/images/L10.webp", "/images/d7.webp", "/images/s10.webp", "/images/d3.webp"],
    archive: [
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/2.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/3.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/4.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/7.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/8.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/9.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/11.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/12.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/13.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/14.png",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/15.png",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/16.png",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/17.png",
      "https://media.cmtradingco.com/rippotai_projects/sunder_vihar/18.png",
    ],
  },
  {
    slug: "vinay-khanna-law-chambers-panchsheel-park",
    name: "Vinay Khanna Law Chambers",
    category: "commercial",
    type: "Commercial",
    location: "Panchsheel Park, New Delhi",
    scope: "Planning & Interior Designing",
    status: "Completed",
    cover: "/images/p_khanna.webp",
    banner: "/images/L2.webp",
    shape: "W",
    featured: true,
    summary:
      "Khanna’s Law Firm is shaped as a workplace of clarity, order, and quiet authority. Located in New Delhi, the office is designed to reflect the seriousness of legal practice while remaining welcoming, composed, and contemporary.",
    details: [
      "The interior palette brings together warm wood, muted blue tones, black MS detailing, and fluted glass. Wood adds a sense of familiarity, while blue introduces calm and focus. The sharper metal elements give the space structure, and fluted glass creates privacy without making the office feel enclosed.",
    ],
    gallery: [
      "/images/L2.webp",
      "/images/hero2.webp",
      "/images/d10.webp",
      "/images/L8.webp",
      "/images/s8.webp",
      "/images/d2.webp",
      "/images/s14.webp",
      "/images/d5.webp",
      "/images/sagar.webp",
    ],
    archive: [
      "https://media.cmtradingco.com/rippotai_projects/khanna_law_firm/1.png",
      "https://media.cmtradingco.com/rippotai_projects/khanna_law_firm/2.png",
      "https://media.cmtradingco.com/rippotai_projects/khanna_law_firm/3.png",
      "https://media.cmtradingco.com/rippotai_projects/khanna_law_firm/4.png",
      "https://media.cmtradingco.com/rippotai_projects/khanna_law_firm/5.png",
      "https://media.cmtradingco.com/rippotai_projects/khanna_law_firm/8.png",
      "https://media.cmtradingco.com/rippotai_projects/khanna_law_firm/7.png",
    ],
  },
  {
    slug: "chhabra-marble-and-sanitary-showroom",
    name: "Chhabra Marble & Sanitary Showroom",
    category: "commercial",
    type: "Commercial",
    location: "Paschim Vihar, New Delhi",
    scope: "Interior Design, Space Planning, Display Design, Lighting Design",
    status: "Completed",
    cover: "/images/p_marble.webp",
    banner: "/images/fb2.webp",
    shape: "H",
    featured: true,
    summary:
      "The Chhabra Marble & Sanitary Showroom is designed as an experience-led retail space, where products are not simply displayed but carefully staged to be understood, compared, and imagined within real settings.",
    details: [
      "The interior uses a restrained palette, textured surfaces, vertical fins, and controlled lighting to create a refined backdrop for marble, sanitaryware, and fittings. Material contrast gives each category its own identity, while maintaining a consistent visual language across the showroom.",
    ],
    gallery: [
      "/images/fb2.webp",
      "/images/L5.webp",
      "/images/s16.webp",
      "/images/d4.webp",
      "/images/L11.webp",
      "/images/d9.webp",
      "/images/s11.webp",
    ],
    archive: [
      "https://media.cmtradingco.com/rippotai_projects/chhabra-marble-sanitary-showroom/1.jpeg",
      "https://media.cmtradingco.com/rippotai_projects/chhabra-marble-sanitary-showroom/2.jpeg",
      "https://media.cmtradingco.com/rippotai_projects/chhabra-marble-sanitary-showroom/5.jpeg",
      "https://media.cmtradingco.com/rippotai_projects/chhabra-marble-sanitary-showroom/6.jpeg",
      "https://media.cmtradingco.com/rippotai_projects/chhabra-marble-sanitary-showroom/7.jpeg",
      "https://media.cmtradingco.com/rippotai_projects/chhabra-marble-sanitary-showroom/8.jpeg",
      "https://media.cmtradingco.com/rippotai_projects/chhabra-marble-sanitary-showroom/9.jpeg",
    ],
  },
  {
    slug: "sky-view-restaurant-lucknow",
    name: "Sky View Restaurant",
    category: "hospitality",
    type: "Hospitality",
    location: "Lucknow, Uttar Pradesh",
    scope: "Planning & Designing",
    status: "Completed",
    cover: "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/cover_image.png",
    banner: "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/banner.png",
    shape: "H",
    featured: true,
    summary:
      "Sky View Café is a hospitality project designed on a terrace level, envisioned as a vibrant social space that blends openness, greenery, and experiential design.",
    details: [
      "The planning focuses on creating a dynamic yet comfortable environment, offering a balance between open-air seating and enclosed seating areas to suit varying user preferences and weather conditions.",
      "The layout integrates a dedicated mocktail bar as a central attraction, enhancing the interactive experience of the café. Multiple photo points are strategically designed throughout the space, encouraging visual engagement and making the café a memorable destination for visitors. A garden setting further enriches the ambience, introducing natural elements that soften the built environment and create a relaxed, refreshing atmosphere.",
      "Material selection plays a key role in defining the character of the café. An MS frame forms the structural base, paired with glass to maintain visual openness and uninterrupted views. Terracotta jali elements are incorporated to add texture, warmth, and cultural relevance, while also assisting with ventilation and light filtration. The combination of these materials results in a contemporary yet contextually rooted design.",
      "Overall, Sky View Café is designed as an inviting rooftop destination that merges functionality, aesthetics, and experiential design, offering patrons a lively yet comfortable dining experience.",
    ],
    gallery: [
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/1.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/2.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/3.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/4.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/5.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/6.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/7.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/8.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/9.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/10.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/11.png",
      "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/12.png",
    ],
    archive: [],
  },
  {
    slug: "goels-residence-gurugram",
    name: "The House Within",
    category: "residential",
    type: "Residential",
    location: "Sector 5, Gurgaon, Haryana",
    scope: "Interior Designing",
    status: "Completed",
    cover: "https://media.cmtradingco.com/rippotai_projects/goyal_residence/cover_image.png",
    banner: "https://media.cmtradingco.com/rippotai_projects/goyal_residence/banner.png",
    shape: "W",
    featured: true,
    summary:
      "Goyal Residence in Gurugram is envisioned as a contemporary living space where bold materials and refined detailing come together in quiet harmony.",
    details: [
      "The walls feature an imagined dado, finished in glossy black laminate, lending depth, contrast, and a subtle play of reflections to the interiors. Structural columns are enveloped in sculptural POP-masking forms, adding rhythm and architectural character to the space. Select walls are layered with wallpaper and complemented by warm wooden accents, creating a balance between texture, warmth, and modern sophistication.",
      "The residence reflects a thoughtful composition of materials and forms, resulting in interiors that feel dynamic yet composed—contemporary in expression and comfortable in experience.",
    ],
    gallery: [
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/1.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/2.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/3.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/4.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/5.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/6.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/7.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/8.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/9.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/10.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/11.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/12.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/13.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/14.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/15.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/16.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/17.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/18.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/19.jpg",
      "https://media.cmtradingco.com/rippotai_projects/goyal_residence/20.jpg",
    ],
    archive: [],
  },
  {
    slug: "sehaj",
    name: "Sehaj",
    category: "residential",
    type: "Residential",
    location: "Vindyachal Apartments, Paschim Vihar",
    scope: "Turnkey",
    status: "Completed",
    cover: "https://media.cmtradingco.com/rippotai_projects/sehaj/cover_image.jpg",
    banner: "https://media.cmtradingco.com/rippotai_projects/sehaj/banner.jpg",
    shape: "V",
    featured: true,
    summary:
      "Sehaj is designed around ease, where movement feels natural and uninterrupted. Planned for elderly users, the home avoids a clinical approach, focusing instead on intuitive living. Wider doorways, gentle slopes, and a barrier-free layout allow seamless circulation, while open planning enhances continuity.",
    details: [
      "The bathroom follows the same logic, with anti-skid flooring, grab bars, a seating ledge, and accessible fixtures supporting safety and independence. Soft, neutral materials create a calm environment without excess. Rather than adding elements, Sehaj removes friction shaping a home that quietly supports everyday life with dignity, comfort, and simplicity.",
    ],
    gallery: [
      "https://media.cmtradingco.com/rippotai_projects/sehaj/1.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/2.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/3.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/4.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/5.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/6.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/7.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/8.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/9.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/10.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/11.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/12.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/13.jpg",
      "https://media.cmtradingco.com/rippotai_projects/sehaj/14.jpg",
    ],
    archive: [],
  },
  {
    slug: "khannas-residence-geetanjali-marg",
    name: "Khanna’s Residence",
    category: "residential",
    type: "Residential",
    location: "Geetanjali Marg, New Delhi",
    scope: "Terrace & Bespoke Furniture",
    status: "Completed",
    cover: "https://media.cmtradingco.com/rippotai_projects/b19_geetanjali_residence/cover_image.png",
    banner: "https://media.cmtradingco.com/rippotai_projects/b19_geetanjali_residence/banner.png",
    shape: "V",
    featured: true,
    summary:
      "B19 Residence is a study in minimal luxury, where clean lines and subtle materiality meet bespoke craftsmanship. Wood and veneer form the base language, enriched with touches of marble and gold that whisper understated opulence.",
    details: [
      "Custom furniture—including TV panels, beds, side tables, and consoles—is designed to balance elegance with functionality, each piece curated to complement the home’s refined aesthetic.",
      "The terrace unfolds as a serene outdoor retreat, featuring a pergola seating arrangement crafted in black metal and glass, softened by warm wooden elements. Together, they create a space that invites both repose and conversation under the open sky.",
      "The temple, a spiritual anchor within the residence, rises in quiet grandeur. A marble backdrop is paired with frosted glass and wood veneer pocket doors of monumental height, filtering light while honoring the sanctity of the space. Every detail is designed to balance reverence, material honesty, and visual poetry.",
    ],
    gallery: [
      "https://media.cmtradingco.com/rippotai_projects/b19_geetanjali_residence/1.png",
      "https://media.cmtradingco.com/rippotai_projects/b19_geetanjali_residence/2.png",
      "https://media.cmtradingco.com/rippotai_projects/b19_geetanjali_residence/3.png",
      "https://media.cmtradingco.com/rippotai_projects/b19_geetanjali_residence/4.png",
      "https://media.cmtradingco.com/rippotai_projects/b19_geetanjali_residence/5.png",
      "https://media.cmtradingco.com/rippotai_projects/b19_geetanjali_residence/6.png",
    ],
    archive: [],
  },
  {
    slug: "singhs-residence",
    name: "Singh’s Residence",
    category: "residential",
    type: "Residential",
    location: "GK-2, New Delhi",
    scope: "Interior Designing",
    status: "Completed",
    cover: "https://media.cmtradingco.com/rippotai_projects/singh_residence/cover_image.png",
    banner: "https://media.cmtradingco.com/rippotai_projects/singh_residence/banner.png",
    shape: "V",
    featured: false,
    summary:
      "Singh’s Residence is a luxurious private home located in the heart of South Delhi, envisioned as an expression of elegance and refined living. The interiors are designed in a rich luxury theme, where opulence is achieved through carefully curated materials rather than excess.",
    details: [
      "Wood, veneers, and Italian marble form the core material palette, creating a layered composition of warmth and grandeur. Mirrors are strategically incorporated to enhance spatial depth and amplify light, while wooden elements bring balance and tactile comfort to the lavish setting.",
      "The residence reflects a harmonious blend of material richness and thoughtful detailing, resulting in interiors that feel sophisticated, expansive, and timeless—crafted to elevate everyday living.",
    ],
    gallery: [
      "https://media.cmtradingco.com/rippotai_projects/singh_residence/1.png",
      "https://media.cmtradingco.com/rippotai_projects/singh_residence/2.png",
      "https://media.cmtradingco.com/rippotai_projects/singh_residence/3.png",
      "https://media.cmtradingco.com/rippotai_projects/singh_residence/4.png",
      "https://media.cmtradingco.com/rippotai_projects/singh_residence/5.png",
      "https://media.cmtradingco.com/rippotai_projects/singh_residence/7.png",
    ],
    archive: [],
  },
  {
    slug: "kohlis-residence-shalimar-bagh",
    name: "Kohli’s Residence",
    category: "residential",
    type: "Residential",
    location: "Shalimar Bagh, New Delhi",
    scope: "Interior Designing",
    status: "Completed",
    cover: "https://media.cmtradingco.com/rippotai_projects/kohli_residence/cover_image.png",
    banner: "https://media.cmtradingco.com/rippotai_projects/kohli_residence/cover_image.png",
    shape: "V",
    featured: false,
    summary:
      "Kohli’s Residence is a thoughtfully designed home that balances traditional Indian aesthetics with modern functional elements. Rich woodwork forms the primary material language, adding warmth and cultural character to the interiors.",
    details: [
      "Modern interventions such as glass partitions, bay windows, and streamlined fixtures are integrated seamlessly, ensuring functionality and enhancing natural light and openness. The result is a home that celebrates heritage-inspired design while accommodating contemporary living needs.",
    ],
    gallery: [
      "https://media.cmtradingco.com/rippotai_projects/kohli_residence/1.jpeg",
      "https://media.cmtradingco.com/rippotai_projects/kohli_residence/2.png",
      "https://media.cmtradingco.com/rippotai_projects/kohli_residence/3.jpeg",
    ],
    archive: [],
  },
  {
    slug: "moksh-dham-aligarh",
    name: "Moksh Dham, Aligarh",
    category: "institutional",
    type: "Institutional",
    location: "Aligarh, Uttar Pradesh",
    scope: "Planning & Designing",
    status: "Completed",
    cover: "/images/p_moksh.webp",
    banner: "/images/hero1.webp",
    shape: "F",
    featured: false,
    summary:
      "Moksh Dhaam is a crematorium project envisioned with a deep focus on ritual, movement, and spatial sequencing.",
    details: [
      "The planning is guided by pathway planning principles, where each space is arranged in accordance with the chronological steps followed during the cremation process. This approach ensures clarity, dignity, and ease of movement for users during a highly sensitive experience. All functional spaces are organized around a central Shiva idol, establishing a strong spiritual and symbolic axis for the site. At the heart of the complex lies an elevated mound that acts as the visual and conceptual focal point. Beneath this mound, administrative offices are thoughtfully integrated, allowing operational functions to remain discreet while maintaining the sanctity of the upper ceremonial spaces.",
      "The design places significant emphasis on landscape and environmental sensitivity. A substantial amount of existing vegetation on the site has been retained and incorporated into the overall planning, creating a serene, contemplative environment. The presence of greenery helps soften the industrial nature of the typology while offering a sense of calm, reflection, and continuity with nature.",
      "Moksh Dhaam represents a balanced integration of ritual-based planning, spiritual symbolism, and sustainable site responsiveness, resulting in a crematorium that is both functional and respectful in its architectural expression.",
    ],
    gallery: [
      "/images/hero1.webp",
      "/images/fb3.webp",
      "/images/L1.webp",
      "/images/d6.webp",
      "/images/s7.webp",
      "/images/fb1.webp",
      "/images/L7.webp",
    ],
    archive: [
      "https://media.cmtradingco.com/rippotai_projects/moksh_dhaam/1.png",
      "https://media.cmtradingco.com/rippotai_projects/moksh_dhaam/2.png",
      "https://media.cmtradingco.com/rippotai_projects/moksh_dhaam/3.png",
      "https://media.cmtradingco.com/rippotai_projects/moksh_dhaam/4.png",
      "https://media.cmtradingco.com/rippotai_projects/moksh_dhaam/5.png",
      "https://media.cmtradingco.com/rippotai_projects/moksh_dhaam/6.png",
      "https://media.cmtradingco.com/rippotai_projects/moksh_dhaam/7.png",
      "https://media.cmtradingco.com/rippotai_projects/moksh_dhaam/8.png",
      "https://media.cmtradingco.com/rippotai_projects/moksh_dhaam/9.png",
      "https://media.cmtradingco.com/rippotai_projects/moksh_dhaam/10.png",
    ],
  },
  {
    slug: "nagpals-residence-pitampura",
    name: "Nagpal’s Residence",
    category: "residential",
    type: "Residential",
    location: "Pitampura, New Delhi",
    scope: "Façade & Interior Designing",
    status: "Completed",
    cover: "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/cover_image.png",
    banner: "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/banner.png",
    shape: "V",
    featured: false,
    summary:
      "Nagpal’s Residence is a mixed-use project located in Pitampura, New Delhi, where the design challenge was to seamlessly integrate a commercial store within a residential building.",
    details: [
      "The planning and façade treatment were approached holistically to ensure visual continuity between the commercial and residential functions, while still maintaining a clear architectural identity. The façade design is composed using ACP panels, MS members, and tiles, arranged in a balanced composition that unifies both uses of the building. A neutral color palette of greys and beiges was selected to achieve a contemporary, refined appearance while ensuring longevity and contextual harmony within the urban fabric.",
      "The interior spaces are inspired by a contemporary design theme, emphasizing clean lines, functionality, and warmth. Wood is used as the primary material, complemented by other subtle design elements to create a comfortable and modern living environment. The interiors are designed to reflect understated elegance while catering to everyday residential needs.",
      "Overall, the project demonstrates a thoughtful approach to mixed-use design, combining cohesive façade articulation with well-planned contemporary interiors.",
    ],
    gallery: [
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/1.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/2.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/3.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/4.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/5.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/6.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/7.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/8.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/9.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/10.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/11.png",
      "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/12.png",
    ],
    archive: [],
  },
  {
    slug: "bangas-residence",
    name: "Banga’s Residence",
    category: "residential",
    type: "Residential",
    location: "Paschim Vihar, New Delhi",
    scope: "Terrace & Bespoke Furniture",
    status: "Completed",
    cover: "/images/p_banga.webp",
    banner: "/images/fb4.webp",
    shape: "W",
    featured: true,
    summary:
      "Banga’s Residence is a refined exploration of modern minimalism, where clean architectural lines meet warm material tones. The design focuses on simplicity, functionality, and a subtle sense of luxury through carefully selected finishes.",
    details: [
      "The project emphasizes bespoke furniture crafted to align with the home’s understated aesthetic. Elements such as TV panels, beds, and storage units are designed with precision, using wood and veneer to create a cohesive visual language.",
      "The terrace is developed as a calm outdoor extension, featuring a pergola seating arrangement in metal and wood that balances openness with comfort. The overall design approach prioritizes clarity, durability, and a timeless modern appeal.",
    ],
    gallery: [
      "/images/fb4.webp",
      "/images/L12.webp",
      "/images/L6.webp",
      "/images/s12.webp",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/1.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/2.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/3.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/4.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/5.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/6.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/7.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/8.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/9.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/10.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/11.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/12.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/13.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/14.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/15.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/16.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/17.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/18.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/19.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/20.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/21.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/22.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/23.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/24.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/25.png",
      "https://media.cmtradingco.com/rippotai_projects/bangas_residence/26.png",
    ],
    archive: [],
  },
  {
    slug: "guptas-residence",
    name: "Gupta’s Residence",
    category: "residential",
    type: "Residential",
    location: "GK-54, New Delhi",
    scope: "Interior Designing",
    status: "Completed",
    cover: "https://media.cmtradingco.com/rippotai_projects/gupta_residence/cover_image.png",
    banner: "https://media.cmtradingco.com/rippotai_projects/gupta_residence/banner.png",
    shape: "H",
    featured: false,
    summary:
      "Gupta’s Residence is a serene ode to Neo-Classical elegance, where every corner whispers timeless grace. Soft POP moldings trace delicate lines along walls and ceilings, while a gentle palette of whites and beiges bathes the interiors in quiet sophistication.",
    details: [
      "The office space emerges as a warm retreat, its walls clad in rich wood, grounding the home with texture and depth. Every detail, from molding to material, is curated to balance classical refinement with modern comfort, creating a home that feels both majestic and intimately livable—a space where light, color, and form dance in harmony.",
    ],
    gallery: [
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/1.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/2.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/3.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/4.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/5.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/6.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/7.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/8.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/9.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/10.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/11.png",
      "https://media.cmtradingco.com/rippotai_projects/gupta_residence/12.png",
    ],
    archive: [],
  },
  {
    slug: "town-property-office-panchsheel-park",
    name: "Town Property Office",
    category: "commercial",
    type: "Commercial",
    location: "Panchsheel Park, New Delhi",
    scope: "Planning & Designing",
    status: "Completed",
    cover: "https://media.cmtradingco.com/rippotai_projects/town_property_office/cover_image.png",
    banner: "https://media.cmtradingco.com/rippotai_projects/town_property_office/banner.png",
    shape: "H",
    featured: false,
    summary:
      "Town Property Office is conceived as a refined workspace for property management and real estate services, where subtle elegance meets functional sophistication. The interiors are composed in soft, muted tones, thoughtfully punctuated with warm wooden accents that bring a sense of tactility and calm to the environment.",
    details: [
      "Modern lighting systems, including sleek stretch lights, animate the space and highlight architectural elements, while the marble-finished flooring elevates the overall sense of grandeur. The office is designed to strike a balance between professionalism and comfort, offering a workspace that feels both prestigious and inviting for clients and staff alike.",
    ],
    gallery: [
      "https://media.cmtradingco.com/rippotai_projects/town_property_office/1.png",
      "https://media.cmtradingco.com/rippotai_projects/town_property_office/2.png",
      "https://media.cmtradingco.com/rippotai_projects/town_property_office/3.png",
      "https://media.cmtradingco.com/rippotai_projects/town_property_office/4.png",
      "https://media.cmtradingco.com/rippotai_projects/town_property_office/5.png",
      "https://media.cmtradingco.com/rippotai_projects/town_property_office/6.png",
      "https://media.cmtradingco.com/rippotai_projects/town_property_office/7.png",
      "https://media.cmtradingco.com/rippotai_projects/town_property_office/8.png",
    ],
    archive: [],
  },
  {
    slug: "cmrr-headquarters",
    name: "CMRR Headquarters",
    category: "commercial",
    type: "Commercial",
    location: "Paschim Vihar, New Delhi",
    scope: "Planning & Designing",
    status: "Completed",
    cover: "https://media.cmtradingco.com/rippotai_projects/cmrr_headquarters/cover_image.png",
    banner: "https://media.cmtradingco.com/rippotai_projects/cmrr_headquarters/banner.png",
    shape: "F",
    featured: false,
    summary:
      "CMRR Headquarters is a commercial office space designed in Paschim Vihar to accommodate the operational and creative teams of multiple business verticals, including Chhabra Marble and Trading Company, Rocklime Media Management, and Rippotai Architecture.",
    details: [
      "The planning emphasizes efficiency, collaboration, and flexibility to support the diverse working styles of these organizations. The design is rooted in a brutalist architectural concept, celebrating the honesty and rawness of materials. Exposed concrete is used extensively across walls, floors, and ceilings, forming the primary visual language of the space. All electrical conduits, piping, and services are intentionally left exposed, reinforcing the principle of “truth to materials” and eliminating unnecessary surface treatments.",
      "This raw industrial aesthetic is balanced through careful spatial planning and proportion, ensuring that the environment remains functional, comfortable, and inspiring for daily work. The resulting office reflects a bold, unfiltered architectural expression that aligns with the creative and construction-oriented nature of the firms it houses.",
    ],
    gallery: [
      "https://media.cmtradingco.com/rippotai_projects/cmrr_headquarters/1.png",
      "https://media.cmtradingco.com/rippotai_projects/cmrr_headquarters/2.png",
      "https://media.cmtradingco.com/rippotai_projects/cmrr_headquarters/3.png",
      "https://media.cmtradingco.com/rippotai_projects/cmrr_headquarters/4.png",
      "https://media.cmtradingco.com/rippotai_projects/cmrr_headquarters/5.png",
      "https://media.cmtradingco.com/rippotai_projects/cmrr_headquarters/6.png",
    ],
    archive: [],
  },
];

export const projectCategories = ["residential", "commercial", "hospitality", "institutional"] as const;
