import type { Project } from "./types";

/**
 * Portfolio index. Order = order on /projects. `shape` is the planned grid tile:
 * F = full-bleed, W = wide (65%), H = horizontal (half), V = vertical (35%).
 * Local covers live in /public/images; the rest load from the project CDN.
 */
export const projects: Project[] = [
  {
    slug: "tropical-home",
    name: "Tropical Home",
    category: "residential",
    type: "Residential",
    cover: "/images/p_tropical.webp",
    shape: "F",
    featured: true,
  },
  {
    slug: "the-inner-house",
    name: "The Inner House",
    category: "residential",
    type: "Residential",
    cover: "/images/p_inner.webp",
    shape: "V",
    featured: true,
  },
  {
    slug: "vinay-khanna-law-chambers",
    name: "Vinay Khanna Law Chambers",
    category: "commercial",
    type: "Commercial",
    cover: "/images/p_khanna.webp",
    shape: "W",
    featured: true,
  },
  {
    slug: "chhabra-marble-sanitary-showroom",
    name: "Chhabra Marble & Sanitary Showroom",
    category: "commercial",
    type: "Commercial",
    cover: "/images/p_marble.webp",
    shape: "H",
    featured: true,
  },
  {
    slug: "sky-view-restaurant",
    name: "Sky View Restaurant",
    category: "hospitality",
    type: "Hospitality",
    cover: "https://media.cmtradingco.com/rippotai_projects/sky_view_cafe/cover_image.png",
    shape: "H",
    featured: false,
  },
  {
    slug: "the-house-within",
    name: "The House Within",
    category: "residential",
    type: "Residential",
    cover: "https://media.cmtradingco.com/rippotai_projects/goyal_residence/cover_image.png",
    shape: "W",
    featured: false,
  },
  {
    slug: "sehaj",
    name: "Sehaj",
    category: "residential",
    type: "Residential",
    cover: "https://media.cmtradingco.com/rippotai_projects/sehaj/cover_image.jpg",
    shape: "V",
    featured: false,
  },
  {
    slug: "khannas-residence",
    name: "Khanna’s Residence",
    category: "residential",
    type: "Residential",
    cover: "https://media.cmtradingco.com/rippotai_projects/b19_geetanjali_residence/cover_image.png",
    shape: "V",
    featured: false,
  },
  {
    slug: "singhs-residence",
    name: "Singh’s Residence",
    category: "residential",
    type: "Residential",
    cover: "https://media.cmtradingco.com/rippotai_projects/singh_residence/cover_image.png",
    shape: "V",
    featured: false,
  },
  {
    slug: "kohlis-residence",
    name: "Kohli’s Residence",
    category: "residential",
    type: "Residential",
    cover: "https://media.cmtradingco.com/rippotai_projects/kohli_residence/cover_image.png",
    shape: "V",
    featured: false,
  },
  {
    slug: "moksh-dham-aligarh",
    name: "Moksh Dham, Aligarh",
    category: "institutional",
    type: "Institutional",
    cover: "/images/p_moksh.webp",
    shape: "F",
    featured: true,
  },
  {
    slug: "nagpals-residence",
    name: "Nagpal’s Residence",
    category: "residential",
    type: "Residential",
    cover: "https://media.cmtradingco.com/rippotai_projects/nagpal_residence/cover_image.png",
    shape: "V",
    featured: false,
  },
  {
    slug: "bangas-residence",
    name: "Banga’s Residence",
    category: "residential",
    type: "Residential",
    cover: "/images/p_banga.webp",
    shape: "W",
    featured: true,
  },
  {
    slug: "guptas-residence",
    name: "Gupta’s Residence",
    category: "residential",
    type: "Residential",
    cover: "https://media.cmtradingco.com/rippotai_projects/gupta_residence/cover_image.png",
    shape: "H",
    featured: false,
  },
  {
    slug: "town-property-office",
    name: "Town Property Office",
    category: "commercial",
    type: "Commercial",
    cover: "https://media.cmtradingco.com/rippotai_projects/town_property_office/cover_image.png",
    shape: "H",
    featured: false,
  },
  {
    slug: "cmrr-headquarters",
    name: "CMRR Headquarters",
    category: "commercial",
    type: "Commercial",
    cover: "https://media.cmtradingco.com/rippotai_projects/cmrr_headquarters/cover_image.png",
    shape: "F",
    featured: false,
  },
];

export const projectCategories = ["residential", "commercial", "hospitality", "institutional"] as const;
